name: app_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  cloud_firestore: ^6.1.1
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  gap: ^3.0.1
  file_picker: ^10.3.8
  path_provider: ^2.1.5

# flutter_native_splash:
#   android_12:
#     image: "assets/img/icons/brand_icon_a12.png"
#   icon_background_color: "#000000"
#   android: true
#   ios: true
#   web: false
#   color: "#000000"
#   image: "assets/img/icons/brand_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

#   flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/img/icons/app_icon.png"
#   remove_alpha_ios: true
#   adaptive_icon_background: "#000000"
#   adaptive_icon_foreground: "assets/img/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/document/
    - assets/img/
    - assets/sound/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
  #   - family: InterBlack
  #     fonts:
  #       - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
  #   - family: Lobster
  #     fonts:
  #       - asset: assets/fonts/Lobster/Lobster-Regular.ttf
  #   - family: Marvel
  #     fonts:
  #       - asset: assets/fonts/Marvel/Marvel-Regular.ttf
